window.AnonymousRPG = window.AnonymousRPG || {};
AnonymousRPG.Core = AnonymousRPG.Core || {};
(function(Core,Data){
const DEFAULT_TARGET=3;
const GOAL_CHAINS={mara:[{text:"안정적인 곡물 공급 유지",target:3,actions:["시장 거래","창고 장부 확인","곡물 판매"]},{text:"시장 재고 기록 정리",target:2,actions:["창고 장부 확인","시장 거래"]}],jonas:[{text:"부두의 이상 화물 확인",target:3,actions:["하역 작업","화물 목록 대조","야간 선박 감시"]},{text:"부두 작업자와 화물 기록 공유",target:2,actions:["화물 목록 대조","야간 선박 감시"]}],serin:[{text:"오류가 있는 기록 추적",target:3,actions:["공문서 대조","토지 기록 조사"]},{text:"공개 기록 보존 상태 점검",target:2,actions:["공문서 대조","토지 기록 조사"]}],darma:[{text:"농촌 운송로 유지",target:3,actions:["농촌 생산 확인","운송 협상","마을 회의"]},{text:"농촌 비축량 확보",target:2,actions:["농촌 생산 확인","운송 협상"]}],ibrahim:[{text:"시장 치안 유지",target:3,actions:["시장 순찰","골목 순찰","야간 경계"]},{text:"시장 순찰 배치 개선",target:2,actions:["시장 순찰","골목 순찰"]}],marta:[{text:"소문과 손님의 흐름 관리",target:3,actions:["여관 준비","손님 응대","손님들의 소문 기록"]},{text:"여관 정보 교환망 정비",target:2,actions:["손님 응대","손님들의 소문 기록"]}],orel:[{text:"도시 시설 수리",target:3,actions:["시장 시설 수리","부두 시설 수리"]},{text:"공공 시설 안전 점검",target:2,actions:["시장 시설 수리","부두 시설 수리"]}]};
function chainFor(id,npc){return GOAL_CHAINS[id]||[{text:npc.goal||"현재 맡은 일을 끝까지 수행",target:Math.max(1,Number(npc.goalTarget)||DEFAULT_TARGET),actions:[]}];}
function makeState(id,npc,i){const c=chainFor(id,npc),x=Math.max(0,Math.min(c.length-1,Number(i)||0)),d=c[x];return{id:"goal-"+id+"-"+x,chainIndex:x,status:"active",progress:0,target:Math.max(1,Number(d.target)||DEFAULT_TARGET),organization:npc.faction||null,priority:1,actions:d.actions.slice(),goalText:d.text,lastProgressMinute:null,completedAt:null,blockedAt:null,blockedReason:null,lastReviewMinute:null,lastReviewReason:null,replanCount:0,replanCooldownUntil:null,completedGoals:[],nextGoal:null};}
function ensure(state){Object.keys(state.npcs||{}).forEach(id=>{const n=state.npcs[id],c=chainFor(id,n);if(!n.goalState||typeof n.goalState!=="object")n.goalState=makeState(id,n,0);const g=n.goalState,i=Math.max(0,Math.min(c.length-1,Number(g.chainIndex)||0)),d=c[i];g.id=g.id||("goal-"+id+"-"+i);g.chainIndex=i;g.status=["active","blocked","complete","abandoned"].includes(g.status)?g.status:"active";g.progress=Math.max(0,Number(g.progress)||0);g.target=Math.max(1,Number(g.target)||Number(d.target)||DEFAULT_TARGET);g.organization=g.organization||n.faction||null;g.priority=Number.isFinite(Number(g.priority))?Number(g.priority):1;g.actions=Array.isArray(g.actions)?g.actions.slice():d.actions.slice();g.goalText=g.goalText||d.text||n.goal||"현재 맡은 일을 끝까지 수행";g.lastProgressMinute=g.lastProgressMinute==null?null:Number(g.lastProgressMinute);g.completedAt=g.completedAt==null?null:Number(g.completedAt);g.blockedAt=g.blockedAt==null?null:Number(g.blockedAt);g.blockedReason=g.blockedReason||null;g.lastReviewMinute=g.lastReviewMinute==null?null:Number(g.lastReviewMinute);g.lastReviewReason=g.lastReviewReason||null;g.replanCount=Math.max(0,Number(g.replanCount)||0);g.replanCooldownUntil=g.replanCooldownUntil==null?null:Number(g.replanCooldownUntil);g.completedGoals=Array.isArray(g.completedGoals)?g.completedGoals.slice(-8):[];g.nextGoal=g.nextGoal&&typeof g.nextGoal==="object"?g.nextGoal:null;n.goal=g.goalText;});}
function organizationPressure(state,npc){const id=npc&&npc.faction;return id&&state.world.organizations&&state.world.organizations[id]?Number(state.world.organizations[id].goalPressure)||0:0;}
function review(state,id,minute){ensure(state);const n=state.npcs[id];if(!n)return null;const g=n.goalState,p=organizationPressure(state,n),m=Number(minute)||Core.getAbsoluteMinute(state);g.lastReviewMinute=m;if(g.status==="complete")return null;if(p<=-2){if(g.status!=="blocked"){g.status="blocked";g.blockedAt=m;g.blockedReason="조직의 우선순위가 현재 목표와 충돌한다.";g.lastReviewReason=g.blockedReason;return n.name+"의 목표가 일시 중단됐다: "+g.goalText;}if(g.blockedAt!=null&&m-g.blockedAt>=1440&&(g.replanCooldownUntil==null||m>=g.replanCooldownUntil))return replan(state,id,m,"중단 상태가 하루 이상 지속됐다.");return null;}if(g.status==="blocked"){g.status="active";g.blockedAt=null;g.blockedReason=null;g.lastReviewReason="조직 우선순위가 회복됐다.";return n.name+"이(가) 조직의 우선순위 변화에 따라 목표를 재개했다: "+g.goalText;}g.priority=Core.clamp(1+p,0,3);return null;}
function replan(state,id,m,reason){ensure(state);const n=state.npcs[id],g=n&&n.goalState,c=chainFor(id,n);if(!n)return null;if(c.length<2){g.status="abandoned";g.lastReviewMinute=m;g.lastReviewReason=reason||"재계획 가능한 후속 목표가 없음";return n.name+"이(가) 현재 목표를 포기했다: "+g.goalText;}const old=g.goalText,next=(g.chainIndex+1)%c.length,d=c[next];g.completedGoals.push({id:g.id,text:old,status:"abandoned",reason:reason||"목표 재계획",minute:m});g.completedGoals=g.completedGoals.slice(-8);g.chainIndex=next;g.id="goal-"+id+"-"+next+"-"+(g.replanCount+1);g.status="active";g.progress=0;g.target=Math.max(1,Number(d.target)||DEFAULT_TARGET);g.actions=d.actions.slice();g.goalText=d.text;g.priority=1;g.completedAt=null;g.blockedAt=null;g.blockedReason=null;g.lastProgressMinute=null;g.lastReviewMinute=m;g.lastReviewReason=reason||"목표 재계획";g.replanCount+=1;g.replanCooldownUntil=m+10080;g.nextGoal=null;n.goal=g.goalText;return n.name+"이(가) 목표를 재계획했다: "+old+" → "+g.goalText;}
function activateNextGoal(n,g,minute){const d=g.nextGoal;if(!d)return false;g.chainIndex=d.chainIndex;g.id="goal-"+n.id+"-"+d.chainIndex+"-next";g.status="active";g.progress=0;g.target=d.target;g.actions=d.actions.slice();g.goalText=d.goalText;g.priority=1;g.completedAt=null;g.blockedAt=null;g.blockedReason=null;g.lastProgressMinute=null;g.lastReviewMinute=minute;g.lastReviewReason="선행 목표 완료 후 다음 목표를 시작했다.";g.nextGoal=null;n.goal=g.goalText;return true;}
function isRelevant(g,reason){return !g.actions||!g.actions.length||g.actions.indexOf(reason)!==-1;}
function progress(state,id,amount,minute,reason){ensure(state);const n=state.npcs[id];if(!n||!n.goalState)return null;const g=n.goalState,m=Number(minute)||Core.getAbsoluteMinute(state);if(g.status==="complete"&&g.nextGoal){activateNextGoal(n,g,m);}if(g.status!=="active")return review(state,id,m);const reviewEvent=review(state,id,m);if(g.status!=="active")return reviewEvent;if(!isRelevant(g,reason))return reviewEvent;const p=organizationPressure(state,n),delta=Math.max(0,Number(amount)||0)*(p>=2?2:1);if(!delta)return reviewEvent;g.progress=Math.min(g.target,g.progress+delta);g.lastProgressMinute=m;if(g.progress<g.target){const e=n.name+"의 개인 목표가 진행됐다: "+g.goalText+" ["+g.progress+"/"+g.target+"]";return reviewEvent?reviewEvent+" "+e:e;}g.status="complete";g.completedAt=m;g.completedGoals.push({id:g.id,text:g.goalText,status:"complete",minute:m});g.completedGoals=g.completedGoals.slice(-8);if(n.faction)Core.adjustRelation(state,n.faction,1);const c=chainFor(id,n);if(c.length>1){const next=(g.chainIndex+1)%c.length,d=c[next];g.nextGoal={chainIndex:next,target:Math.max(1,Number(d.target)||DEFAULT_TARGET),actions:d.actions.slice(),goalText:d.text};return n.name+"이(가) 개인 목표를 달성했다: "+g.goalText+". 다음 목표는 "+d.text+"이다.";}return n.name+"이(가) 개인 목표를 달성했다: "+g.goalText+(reason?" ("+reason+")":"");}
function status(state,id){ensure(state);const n=state.npcs[id];if(!n)return null;const g=n.goalState;return{id,name:n.name,goal:g.goalText||n.goal,status:g.status,progress:g.progress,target:g.target,priority:g.priority,organization:g.organization,blockedReason:g.blockedReason,replanCount:g.replanCount,completedAt:g.completedAt,completedGoals:g.completedGoals.slice(),nextGoal:g.nextGoal?g.nextGoal.goalText:null};}
Core.ensureNPCGoals=ensure;Core.progressNPCGoal=progress;Core.reviewNPCGoal=review;Core.replanNPCGoal=replan;Core.getNPCGoalStatus=status;Core.npcGoalChains=GOAL_CHAINS;
})(AnonymousRPG.Core,AnonymousRPG.Data);
