const SAVE_KEY="anonymous_chronicles_save_v2";
const PLACES={market:{name:"도시 북문 시장",travelFrom:{riverside:20,alley:10,archive:15,hills:90}},riverside:{name:"강변 부두",travelFrom:{market:20,alley:10,archive:25,hills:110}},alley:{name:"회색 골목",travelFrom:{market:10,riverside:10,archive:20,hills:100}},archive:{name:"서문 기록관",travelFrom:{market:15,riverside:25,alley:20,hills:95}},hills:{name:"구릉 농촌지대",travelFrom:{market:90,riverside:110,alley:100,archive:95}}};
const NPCS={mara:{name:"마라 벨라스",place:"market",trust:0},jonas:{name:"요나스 크렐",place:"riverside",trust:0},serin:{name:"세린 오르도",place:"archive",trust:0},darma:{name:"다르마 누르",place:"hills",trust:0},ibrahim:{name:"이브라힘 살릭",place:"market",trust:0},marta:{name:"마르타 켈",place:"alley",trust:0},orel:{name:"오렐 다브",place:"alley",trust:0}};
const state={player:{name:"에바 로셀",hp:10,maxHp:10,fatigue:2,maxFatigue:10,money:18,place:"market",inventory:{note:1,knife:1}},world:{day:0,minutes:360,grainSupply:72,tension:25,security:62,trustInAdministration:68,rumorPressure:0,flags:{marketRumor:false,recordInconsistency:false,nightCargo:false,warehouseSuspicion:false,ruralDelegation:false},discovered:[],cases:[]},npcs:structuredClone(NPCS),log:[]};
const CASES={
 "grain-warehouse":{title:"닫힌 창고의 곡물",summary:"곡물 부족과 함께 일부 창고의 출입이 비정상적으로 줄었다.",trigger:()=>state.world.flags.warehouseSuspicion,choices:[
  {id:"audit",label:"공식 장부 대조",risk:1,run:()=>{state.world.trustInAdministration+=3;state.world.grainSupply+=4;return"공식 기록을 대조한 결과 일부 재고 차이가 확인됐다. 행정 기록에 흔적이 남았다."}},
  {id:"negotiate",label:"상인과 비공식 협상",risk:2,run:()=>{state.player.money+=5;state.world.grainSupply+=2;return"상인들과 직접 조건을 맞췄다. 당장의 공급은 조금 안정됐지만 공식 기록에는 남지 않았다."}},
  {id:"force",label:"창고를 강제로 확인",risk:4,run:()=>{state.world.security-=5;state.world.tension+=5;return"강제로 문을 열었다. 숨겨진 물량 일부는 확인했지만 시장의 긴장도 함께 높아졌다."}}
 ]},
 "night-cargo":{title:"시간표 밖의 배",summary:"예정표에 없는 선박의 움직임이 야간 부두에서 포착됐다.",trigger:()=>state.world.flags.nightCargo,choices:[
  {id:"report",label:"경비대에 보고",risk:1,run:()=>{state.world.security+=3;state.world.trustInAdministration+=2;return"목격 내용을 경비대에 전달했다. 조사 기록이 정식으로 남았다."}},
  {id:"follow",label:"배의 행선지를 추적",risk:3,run:()=>{state.world.rumorPressure++;state.world.discovered.push("cargoRoute");return"부두 밖까지 흔적을 따라갔다. 화물이 북쪽 운송로와 연결된다는 정황을 얻었다."}},
  {id:"ignore",label:"모른 척 지나가기",risk:0,run:()=>{state.world.tension=Math.max(0,state.world.tension-1);return"당장은 아무 일도 하지 않았다. 그 움직임은 기록되지 않은 채 사라졌다."}}
 ]},
 "land-record":{title:"서로 다른 토지 기록",summary:"같은 토지 번호가 서로 다른 소유자와 날짜로 기록되어 있다.",trigger:()=>state.world.flags.recordInconsistency,choices:[
  {id:"archive",label:"기록관에 정식 보존 요청",risk:1,run:()=>{state.world.trustInAdministration+=4;return"기록 사본을 보존하도록 요청했다. 이후 조사자가 확인할 수 있는 흔적이 남았다."}},
  {id:"owner",label:"현재 소유자에게 직접 확인",risk:2,run:()=>{state.player.money+=2;state.world.discovered.push("landWitness");return"현 소유자에게서 오래된 거래 증언을 들었다. 문서보다 오래된 사정이 있다는 것을 알게 됐다."}},
  {id:"alter",label:"기록의 일부를 몰래 수정",risk:5,run:()=>{state.world.trustInAdministration-=6;state.world.tension+=2;return"기록 일부를 건드렸다. 당장은 문제가 없지만 행정 신뢰가 약간 흔들렸다."}}
 ]}
};
function clamp(v,a,b){return Math.max(a,Math.min(b,v))} function time(){return `${String(Math.floor(state.world.minutes/60)).padStart(2,"0")}:${String(state.world.minutes%60).padStart(2,"0")}`} function part(){const h=Math.floor(state.world.minutes/60);return h<6?"심야":h<9?"이른 아침":h<12?"오전":h<14?"정오":h<18?"오후":h<21?"해질녘":"밤"}
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify(state))} function load(){const raw=localStorage.getItem(SAVE_KEY);if(!raw)return;try{const x=JSON.parse(raw);Object.assign(state,x);state.world.discovered=Array.isArray(x.world.discovered)?x.world.discovered:[];state.world.cases=Array.isArray(x.world.cases)?x.world.cases:[]}catch(e){console.warn("save load failed",e)}}
function addTurn(n,a=null,system=false){state.log.push({time:`${state.world.day+1}일째 · ${time()}`,narrative:n,action:a,system});if(state.log.length>60)state.log.shift();render();save()}
function advance(min){state.world.minutes+=min;while(state.world.minutes>=1440){state.world.minutes-=1440;state.world.day++;if(Math.random()<.45)state.world.grainSupply--;if(Math.random()<.2)state.world.tension++}state.world.grainSupply=clamp(state.world.grainSupply,0,100);state.world.tension=clamp(state.world.tension,0,100)}
function ensureCases(){for(const [id,c] of Object.entries(CASES)){if(c.trigger()&&!state.world.cases.some(x=>x.id===id))state.world.cases.push({id,status:"open",branch:null,attempts:0,createdDay:state.world.day})}}
function deterministic(id,choice){let h=2166136261;for(const ch of `${id}:${choice}:${state.world.day}`){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0)%6+1}
function caseCommand(text){ensureCases();const m=text.match(/(?:사건분기|사건)\s+([a-z-]+|\d+)(?:\s+([a-z-]+|\d+))?/);if(!m)return null;const open=state.world.cases.filter(c=>c.status==="open");let id=m[1];if(/^\d+$/.test(id))id=open[+id-1]?.id;const cs=state.world.cases.find(c=>c.id===id&&c.status==="open");if(!cs)return"그 사건은 진행 중인 사건 목록에 없다.";const def=CASES[id];if(!m[2])return`${def.title} — ${def.summary} 선택지: ${def.choices.map((c,i)=>`${i+1}. ${c.label} [위험 ${c.risk}]`).join(" / ")}`;let ci=m[2];if(/^\d+$/.test(ci))ci=def.choices[+ci-1]?.id;const ch=def.choices.find(c=>c.id===ci);if(!ch)return"유효한 사건 선택지가 아니다.";const roll=deterministic(id,ch.id),need=3+ch.risk;cs.attempts++;cs.branch=ch.id;advance(10);if(roll>=need){cs.status="resolved";const out=ch.run();return`【${def.title}】 ${out} (판정 ${roll}/${need})`}state.world.tension=clamp(state.world.tension+Math.max(1,ch.risk),0,100);if(cs.attempts>=2)cs.status="failed";return`【${def.title}】 ${ch.label}은(는) 원하는 결과를 만들지 못했다. (판정 ${roll}/${need})`}
function move(place){if(place===state.player.place)return"이미 그곳에 있다.";const c=PLACES[state.player.place].travelFrom[place]??10;advance(c);state.player.fatigue=clamp(state.player.fatigue+Math.ceil(c/35),0,10);state.player.place=place;return`${PLACES[place].name}까지 이동했다. 약 ${c}분이 걸렸다.`}
function placeOf(t){for(const [k,v] of [["시장","market"],["부두","riverside"],["강","riverside"],["골목","alley"],["여관","alley"],["기록관","archive"],["기록","archive"],["농촌","hills"],["언덕","hills"]])if(t.includes(k))return v;return null}
function npcOf(t){return Object.entries(state.npcs).find(([id,n])=>t.includes(id)||t.includes(n.name)||t.includes(n.name.slice(0,2)))}
function inspect(){advance(10);const p=state.player.place;if(p==="market")return`곡물 가격은 대략 ${state.world.grainSupply<60?13:10} 정도로 보인다.`;if(p==="riverside")return state.world.flags.nightCargo?"젖은 밧줄과 화물 자국 사이로 예정표와 맞지 않는 흔적이 보인다.":"젖은 밧줄과 화물 자국, 배에서 흘러나온 물자 냄새가 섞여 있다.";if(p==="archive")return state.world.flags.recordInconsistency?"같은 토지 번호가 서로 다른 소유자와 연결되어 있다.":"공개 열람실의 장부들은 정돈되어 있다.";if(p==="hills")return state.world.grainSupply<60?"농촌의 출하량이 줄었다. 흉작만으로 설명하기 어려운 분위기다.":"수확기 직전의 농촌이다. 운송로와 저장고가 중요해 보인다.";return"여관과 작업장, 공동 우물 주변에 사람들이 모여 있다."}
function talk(t){const f=npcOf(t);if(!f)return"주변 사람과 말을 나누었지만 특별한 정보는 얻지 못했다.";const [id,n]=f;if(n.place!==state.player.place)return`${n.name}은(는) 이곳에 없다.`;advance(10);n.trust++;const lines={mara:state.world.grainSupply<65?"곡물이 이상해요. 가격표보다 창고가 더 중요해졌거든요.":"오늘은 아직 괜찮아요. 하지만 며칠 뒤는 모르겠네요.",jonas:state.world.flags.nightCargo?"밤에 움직이는 배가 있었어.":"부두에서 무슨 일이 있었는지는 먼저 누가 봤는지부터 따져야 해.",serin:state.world.flags.recordInconsistency?"그 번호를 어디서 봤는지 알려주면 같이 확인해 볼 수 있어요.":"기록은 읽는 법보다 비교하는 법이 중요해요.",darma:"북동쪽에서 물건이 잘 내려오지 않고 있어.",ibrahim:state.world.security<50?"요즘 시장에서 시끄러운 일이 늘었어.":"문제 생기면 초소에 와. 직접 본 걸 말하면 된다.",marta:"사람들은 여관에 와서 밥보다 이야기를 더 많이 남기지.",orel:"요즘 상자와 자물쇠를 고쳐달라는 주문이 많아졌어."};return`${n.name}: “${lines[id]}”`}
function act(text){const t=text.trim();if(!t)return;let n=caseCommand(t);if(/^사건목록$|^사건 목록$|^cases$/i.test(t)){ensureCases();n=state.world.cases.filter(c=>c.status==="open").map(c=>`${c.id} — ${CASES[c.id].title}`).join(" / ")||"현재 진행 중인 사건이 없다."}else if(n===null){const p=placeOf(t);if(/이동|가자|간다|가 /i.test(t)&&p)n=move(p);else if(/조사|확인|관찰|살펴|수색/.test(t)){n=inspect();if(state.player.place==="archive")state.world.flags.recordInconsistency=true;if(state.player.place==="riverside"&&part()==="밤")state.world.flags.nightCargo=true;if(state.world.grainSupply<58&&state.world.tension>=35)state.world.flags.warehouseSuspicion=true}else if(/대화|말을|묻|설득|협상/.test(t))n=talk(t);else if(/휴식|쉬어|쉬다/.test(t)){advance(60);state.player.fatigue=clamp(state.player.fatigue-2,0,10);n="잠시 쉬었다."}else if(/잠|잔다|숙면/.test(t)){advance(480);state.player.fatigue=Math.max(0,state.player.fatigue-8);state.player.hp=Math.min(state.player.maxHp,state.player.hp+2);n="충분히 쉬었다."}else{advance(15);n=`당신은 ${t}을(를) 시도했다. 당장 눈에 띄는 결과는 없었다.`}}
state.world.trustInAdministration=clamp(state.world.trustInAdministration,0,100);state.world.security=clamp(state.world.security,0,100);ensureCases();addTurn(n,t)}
function esc(s){return String(s).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;")}
function render(){document.getElementById("location").textContent=`세르카 · ${PLACES[state.player.place].name}`;document.getElementById("dateText").textContent=`183년 · ${state.world.day+1}일`;document.getElementById("timeText").textContent=`${part()} ${time()}`;document.getElementById("moneyText").textContent=state.player.money;document.getElementById("hpText").textContent=`${state.player.hp}/${state.player.maxHp}`;document.getElementById("fatigueText").textContent=`${state.player.fatigue}/${state.player.maxFatigue}`;document.getElementById("inventoryList").innerHTML=Object.entries(state.player.inventory).map(([k,v])=>`<li><span>${esc(k)}</span><b>${v}</b></li>`).join("");const known=[...new Set(state.world.discovered)];const open=state.world.cases.filter(c=>c.status==="open").map(c=>`사건: ${CASES[c.id].title}`);document.getElementById("knownList").innerHTML=[...known,...open].map(x=>`<li>${esc(x)}</li>`).join("")||"<li>아직 없음</li>";document.getElementById("storyBody").innerHTML=state.log.map(x=>`<article class="turn"><div class="time">${esc(x.time)}</div>${x.action?`<div class="actionText">${esc(x.action)}</div>`:""}<div class="${x.system?"system":"narrative"}">${esc(x.narrative)}</div></article>`).join("");window.scrollTo(0,document.body.scrollHeight)}
function init(){load();ensureCases();if(!state.log.length){addTurn("비가 그친 새벽이다. 젖은 돌바닥 위로 사람들이 하루를 시작했다. 누구도 당신을 기다리지 않는다.");addTurn("북문 시장에서는 가게마다 곡물 가격이 조금씩 다르다. 광장 건너편에서는 경비대원이 상인의 저울을 확인하고 있다.")}else render();document.getElementById("actionForm").addEventListener("submit",e=>{e.preventDefault();const i=document.getElementById("actionInput");act(i.value);i.value="";i.focus()})}
init();
